"""initial schema

Revision ID: ed0fe9fa4ba2
Revises:
Create Date: 2026-08-03 11:28:39.434875

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed0fe9fa4ba2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("nombre_empresa", sa.String(length=200), nullable=False),
        sa.Column("contacto_nombre", sa.String(length=150), nullable=True),
        sa.Column("contacto_email", sa.String(length=255), nullable=True),
        sa.Column("contacto_telefono", sa.String(length=40), nullable=True),
        sa.Column("plan_contratado", sa.String(length=80), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "activo",
                "suspendido",
                "prospecto",
                name="client_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "fecha_alta",
            sa.Date(),
            server_default=sa.text("CURRENT_DATE"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clients")),
    )
    op.create_index(op.f("ix_clients_estado"), "clients", ["estado"], unique=False)
    op.create_table(
        "sites",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=150), nullable=False),
        sa.Column("direccion", sa.String(length=300), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("latitud", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("longitud", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("responsable_nombre", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "latitud IS NULL OR (latitud >= -90 AND latitud <= 90)",
            name=op.f("ck_sites_latitud_range"),
        ),
        sa.CheckConstraint(
            "longitud IS NULL OR (longitud >= -180 AND longitud <= 180)",
            name=op.f("ck_sites_longitud_range"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_sites_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sites")),
        sa.UniqueConstraint("client_id", "nombre", name="uq_sites_client_id_nombre"),
    )
    op.create_index(op.f("ix_sites_client_id"), "sites", ["client_id"], unique=False)
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("cu_cop_kwh", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column(
            "cargo_fijo_mensual", sa.Numeric(precision=14, scale=2), nullable=False
        ),
        sa.Column(
            "tasa_credito_excedente", sa.Numeric(precision=14, scale=4), nullable=True
        ),
        sa.Column("vigente_desde", sa.Date(), nullable=False),
        sa.Column("vigente_hasta", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cargo_fijo_mensual >= 0", name=op.f("ck_tariffs_cargo_fijo_non_negative")
        ),
        sa.CheckConstraint("cu_cop_kwh >= 0", name=op.f("ck_tariffs_cu_non_negative")),
        sa.CheckConstraint(
            "vigente_hasta IS NULL OR vigente_hasta > vigente_desde",
            name=op.f("ck_tariffs_vigencia_order"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_tariffs_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_index(
        op.f("ix_tariffs_client_id"), "tariffs", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_tariffs_vigente_desde"), "tariffs", ["vigente_desde"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin",
                "tecnico",
                "cliente",
                "solo_lectura",
                name="user_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("client_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role <> 'cliente' OR client_id IS NOT NULL",
            name=op.f("ck_users_cliente_requires_client"),
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
            name=op.f("fk_users_client_id_clients"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index(op.f("ix_users_client_id"), "users", ["client_id"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "gateways",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("numero_serie", sa.String(length=80), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("token_acceso_hash", sa.String(length=255), nullable=True),
        sa.Column("firmware_version", sa.String(length=40), nullable=True),
        sa.Column("ultima_conexion", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ip_actual", sa.String(length=45), nullable=True),
        sa.Column(
            "estado",
            sa.Enum(
                "online",
                "offline",
                name="gateway_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_gateways_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateways")),
        sa.UniqueConstraint("numero_serie", name=op.f("uq_gateways_numero_serie")),
        sa.UniqueConstraint("uuid", name=op.f("uq_gateways_uuid")),
    )
    op.create_index(op.f("ix_gateways_estado"), "gateways", ["estado"], unique=False)
    op.create_index(op.f("ix_gateways_site_id"), "gateways", ["site_id"], unique=False)
    op.create_table(
        "alerts_config",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gateway_id", sa.Uuid(), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "desconexion",
                "voltaje_fuera_rango",
                "factor_potencia_bajo",
                "consumo_excesivo",
                name="alert_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("umbral", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column(
            "canal_notif",
            sa.Enum(
                "email",
                "telegram",
                "whatsapp",
                name="notification_channel",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["gateways.id"],
            name=op.f("fk_alerts_config_gateway_id_gateways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts_config")),
    )
    op.create_index(
        op.f("ix_alerts_config_gateway_id"),
        "alerts_config",
        ["gateway_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alerts_config_tipo"), "alerts_config", ["tipo"], unique=False
    )
    op.create_table(
        "equipment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("gateway_id", sa.Uuid(), nullable=False),
        sa.Column("marca", sa.String(length=100), nullable=True),
        sa.Column("modelo", sa.String(length=100), nullable=True),
        sa.Column(
            "tipo",
            sa.Enum(
                "medidor",
                "analizador",
                "inversor",
                "sensor",
                name="equipment_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("modbus_id", sa.Integer(), nullable=False),
        sa.Column("puerto", sa.String(length=60), nullable=False),
        sa.Column("baudrate", sa.Integer(), nullable=False),
        sa.Column(
            "paridad",
            sa.Enum(
                "N",
                "E",
                "O",
                name="serial_parity",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("bits", sa.Integer(), nullable=False),
        sa.Column("stop_bits", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_registro",
            sa.Enum(
                "holding",
                "input",
                "coil",
                "discrete",
                name="modbus_register_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("direccion_inicial", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("baudrate > 0", name=op.f("ck_equipment_baudrate_positive")),
        sa.CheckConstraint("bits IN (7, 8)", name=op.f("ck_equipment_bits_valid")),
        sa.CheckConstraint(
            "direccion_inicial >= 0",
            name=op.f("ck_equipment_direccion_inicial_non_negative"),
        ),
        sa.CheckConstraint(
            "modbus_id BETWEEN 1 AND 247", name=op.f("ck_equipment_modbus_id_range")
        ),
        sa.CheckConstraint(
            "stop_bits IN (1, 2)", name=op.f("ck_equipment_stop_bits_valid")
        ),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["gateways.id"],
            name=op.f("fk_equipment_gateway_id_gateways"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment")),
        sa.UniqueConstraint(
            "gateway_id", "puerto", "modbus_id", name="uq_equipment_gateway_puerto_id"
        ),
    )
    op.create_index(
        op.f("ix_equipment_gateway_id"), "equipment", ["gateway_id"], unique=False
    )
    op.create_table(
        "variables",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("equipment_id", sa.Uuid(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("registro_modbus", sa.Integer(), nullable=False),
        sa.Column(
            "tipo_dato",
            sa.Enum(
                "int16",
                "uint16",
                "int32",
                "uint32",
                "float32",
                "float64",
                name="modbus_data_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("escala", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("unidad", sa.String(length=20), nullable=True),
        sa.Column("frecuencia_lectura_segundos", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("escala <> 0", name=op.f("ck_variables_escala_not_zero")),
        sa.CheckConstraint(
            "frecuencia_lectura_segundos > 0",
            name=op.f("ck_variables_frecuencia_lectura_positive"),
        ),
        sa.CheckConstraint(
            "registro_modbus >= 0",
            name=op.f("ck_variables_registro_modbus_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("fk_variables_equipment_id_equipment"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variables")),
        sa.UniqueConstraint(
            "equipment_id", "nombre", name="uq_variables_equipment_id_nombre"
        ),
    )
    op.create_index(
        op.f("ix_variables_equipment_id"), "variables", ["equipment_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_variables_equipment_id"), table_name="variables")
    op.drop_table("variables")
    op.drop_index(op.f("ix_equipment_gateway_id"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_alerts_config_tipo"), table_name="alerts_config")
    op.drop_index(op.f("ix_alerts_config_gateway_id"), table_name="alerts_config")
    op.drop_table("alerts_config")
    op.drop_index(op.f("ix_gateways_site_id"), table_name="gateways")
    op.drop_index(op.f("ix_gateways_estado"), table_name="gateways")
    op.drop_table("gateways")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_client_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tariffs_vigente_desde"), table_name="tariffs")
    op.drop_index(op.f("ix_tariffs_client_id"), table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index(op.f("ix_sites_client_id"), table_name="sites")
    op.drop_table("sites")
    op.drop_index(op.f("ix_clients_estado"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
