"""User: a panel login."""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, CheckConstraint, ForeignKey, String, false
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.domain.enums import UserRole
from app.models.mixins import TimestampMixin, UUIDPrimaryKeyMixin
from app.models.types import enum_column

if TYPE_CHECKING:
    from app.models.client import Client


class User(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Someone who signs in to the monitoring panel."""

    __tablename__ = "users"
    __table_args__ = (
        # A `cliente` login that belongs to no client would see everything;
        # the database refuses to store one.
        CheckConstraint(
            "role <> 'cliente' OR client_id IS NOT NULL",
            name="cliente_requires_client",
        ),
    )

    # Stored lowercase so a login cannot be duplicated by changing case; the
    # service layer normalises before writing.
    email: Mapped[str] = mapped_column(String(255), nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[UserRole] = mapped_column(
        enum_column(UserRole, "user_role"), nullable=False, index=True
    )
    # NULL for internal staff (admin, tecnico); mandatory for the `cliente`
    # role, which is scoped to a single client.
    client_id: Mapped[uuid.UUID | None] = mapped_column(
        # RESTRICT, not CASCADE: deleting a client must not silently destroy
        # login accounts. The caller has to deal with them explicitly.
        ForeignKey("clients.id", ondelete="RESTRICT"),
        index=True,
    )
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    # True while the password was generated by the system or set by an
    # administrator rather than chosen by the account owner. The token issued
    # for such an account only reaches the routes needed to replace it.
    must_change_password: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=false()
    )

    client: Mapped["Client | None"] = relationship(back_populates="users", lazy="raise")

    def __repr__(self) -> str:
        return f"<User {self.email!r} ({self.role})>"
